server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          #cuando se trabajo con yaml se debe dejar espacio despues de los :
          default-label: config-server
          uri: https://github.com/joxibe/Microservicios-java
          search-paths: config-data
  application:
    name: config-service