server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          #rama de github
          default-label: eureka
          uri: https://github.com/joxibe/Microservicios-java
          search-paths: config-data
  application:
    name: config-service